FROM ruby:3.3.6

ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

# Node.js & Yarn
RUN apt-get update -qq \
  && apt-get install -y build-essential libpq-dev curl \
  && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
  && apt-get install -y nodejs \
  && npm install -g yarn

WORKDIR /app

RUN gem install bundler
